spring:
    datasource:
        url: jdbc:mysql://localhost:3306/forum?useSSL=false&serverTimezone=UTC
        username: root
        password:
        driver-class-name: com.mysql.cj.jdbc.Driver

    jpa:
        database-platform: org.hibernate.dialect.MySQL8Dialect
        hibernate:
            ddl-auto: update
        show-sql: true
        format-sql: true
