spring:
    datasource:
        url: jdbc:mysql://localhost:3306/forum?useTimezone=true&serverTimezone=UTC
        username: root
        password:
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        database-platform: org.hibernate.dialect.MySQL8Dialect
        hibernate:
            ddl-auto: none
        show-sql: true
        format-sql: true
    flyway:
        baseline-on-migrate: true
        locations: classpath:db/migration